### PR TITLE
Fix invalid JSON

### PR DESCRIPTION
**Pull request by NHellFire**
Causes git BLT to crash.

### CODE REVIEW

**Comment by BangL** [comment]
our blt json parser doesnt care about this, and kami keeps them so he doesnt forget them when adding lines.
we already discussed this

**Comment by NHellFire** [comment]
As I said, it causes latest git BLT to crash.

**Comment by BangL** [comment]
yep, indeed

**Comment by NHellFire** [comment]
So, crashing the entire game with invalid JSON because one of the
developers is too lazy to validate it is fine?

On 26 Apr 2017 17:57, "BangL" <notifications@github.com> wrote:

yep, indeed

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kamikaze94/WolfHUD/pull/246#issuecomment-297475016>,
or mute
the thread

**Comment by BangL** [comment]
no, i mean.. yep, indeed.. it became a problem in the latest blt.

**Comment by Kamikaze94** [comment]
> So, crashing the entire game with invalid JSON because one of the developers is too lazy to validate it is fine?
Hasn't too much to do with beeing lazy, but more of reducing potential causes of problems. And if the interpreter doesn't care, why introduce them?

Now, since the latest update keeps spamming the log (Hell, it's about 6 or 7 mods I have that get almost printed their entire mod.txt like 3 times each load....), guess you have a point here. :)
<br>
@BangL 
> not sure which blt you're using though

Probably this one: https://github.com/JamesWilko/Payday-2-BLT-Lua

**Pull request merged**
