### PR TITLE
some tweaks regarding names and dmg popups

### PR DESCRIPTION
**Pull request by BangL**
- new option to truncate most clan tags from the player names, and replace them with a small dot-symbol
- new options to set a custom bot name color (also affects dmg popups)
- vanilla hud: now shows player ranks in front of the name and in white
- vanilla hud: names will now be truncated/resized depending on length of name and killcounter/accuracy text

### CODE REVIEW

**Comment by Hulkfog** [comment]
Could you add teammate interaction display and timer for default hud from jackhud

**Comment by BangL** [comment]
this still needs some work, i am on it

**Comment by BangL** [comment]
ok, in my opinion its complete and mergable now.
i can rebase and squash it into one commit though, if you want.

**Comment by BangL** [comment]
just found another bug.. still working on it

**Pull request merged**
