### PR TITLE
fixed bug when interaction would sometimes be shorter the they should

### PR DESCRIPTION
**Pull request by luky92**
fixed bug when interaction would sometimes be shorter the they should… in pagers + lockpick and pagers only modes

### CODE REVIEW

**Comment by Kamikaze94** [comment]
Uhm, is the bug you are referring to something unique to your lock modes, or could it be the bahaviour reported in issue #114 ?

**Comment by luky92** [comment]
yeah looks like it is that all the interactions are extra fast or just start in the middle of the interaction circle

**Comment by Kamikaze94** [comment]
In the video linked in the issue, the tie civilian interaction starts with 0.3s remaing.
So the interaction isn't faster, it just starts almost done (around 1.7s headstart), making every shorter interaction instant...

Are you sure, checking for "_interact_expire_t" fixes this? 
I might add a check around all lock modes for the existence of that variable then, and see how that works out....
Still not fully understanding why this happens though...^^

**Comment by luky92** [comment]
Sadly i was unable to reproduce the issiue since the last cuple of days so i can't tell you exacly if the fiz warks although it seemd to fix the issiue the first time i encountered it

**Comment by dribbleondo** [comment]
The Interaction bug has returned -_-
https://clips.twitch.tv/PlayfulBoldMeatloafCharlietheUnicorn

Captured on Stream, but is known to affect Panic Room also.

**Comment by BangL** [comment]
actual fix: #201

**Pull request closed without merging**
